services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true