services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    volumes:
      - /mnt/Pool1/Config/Zflix/sonarr:/config
      - /mnt/Pool2/Zflix/medias/tvseries:/tvseries
      - /mnt/Pool2/Zflix/downloads:/downloads
    environment:
      - PUID=${USERID}
      - PGID=${GROUPID}
      - TZ=${TIMEZONE}
    labels:
      traefik.enable: true
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true