version: "2"
services:
    plex:
        image: ghcr.io/linuxserver/plex
        container_name: zbox_plex
        ports:
            - 32400:32400
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ./data/plex/libray:/config
            - ./data/plex/tvseries:/tv
            - ./data/plex/movies:/movies
    deluge:
        image: ghcr.io/linuxserver/deluge
        container_name: zbox_deluge
        ports:
            - 8112:8112
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
        volumes:
            - ./conf/deluge/config:/config
            - ./data/deluge/downloads:/downloads
    jackett:
        image: ghcr.io/linuxserver/jackett
        container_name: zbox_jackett
        ports:
            - 9117:9117
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
        volumes:
            - ./conf/jackett/config:/config
            - ./data/jackett/blackhole:/downloads
    sonarr:
        image: ghcr.io/linuxserver/sonarr
        container_name: zbox_sonarr
        ports:
            - 8989:8989
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
        volumes:
            - ./conf/sonarr/config:/config
            - ./data/sonarr/tvseries:/tv
            - ./data/sonarr/delugedownloads:/downloads
    radarr:
        image: ghcr.io/linuxserver/radarr
        container_name: zbox_radarr
        ports:
            - 7979:7979
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
        volumes:
            - ./conf/radarr/config:/config
            - ./data/radarr/movies:/movies
            - ./data/radarr/delugedownloads:/downloads
    lidarr:
        image: ghcr.io/linuxserver/lidarr
        container_name: zbox_lidarr
        ports:
            - 8686:8686
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
        volumes:
            - ./conf/lidarr/config:/config
            - ./data/lidarr/music:/music
            - ./data/lidarr/delugedownloads:/downloads