services:
  torrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    ports:
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - /mnt/Pool1/Config/Zflix/torrent:/config
      - /mnt/Pool2/Zflix/downloads:/downloads
    environment:
      - PUID=${USERID}
      - PGID=${GROUPID}
      - TZ=${TIMEZONE}
    labels:
      zbox: true
      traefik.http.services.torrent.loadbalancer.server.port: 8080
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true