services:
  filebrowser:
    image: filebrowser/filebrowser
    volumes:
      - /mnt:/srv
    environment:
      - TZ=Europe/Paris
    healthcheck:
      test: curl -f http://localhost || exit 1
      interval: 30s
      timeout: 10s
    labels:
      traefik.enable: true
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true